# Generated by Django 5.2.6 on 2025-11-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0004_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="location",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
