# Generated by Django 5.2.6 on 2025-11-25 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0006_add_contractorrequirement_and_seed"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="main_image",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="project",
            name="project_manager",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="supplier",
            name="specialty",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name="ProjectSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_suppliers",
                        to="supply_chain.project",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_projects",
                        to="supply_chain.supplier",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "supplier")},
            },
        ),
        migrations.AddField(
            model_name="project",
            name="suppliers",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                through="supply_chain.ProjectSupplier",
                to="supply_chain.supplier",
            ),
        ),
    ]
