# Generated by Django 5.2.6 on 2025-11-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0009_project_end_date_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
