# Generated by Django 5.2.6 on 2025-11-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0011_eventimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image_file",
            field=models.ImageField(blank=True, null=True, upload_to="events/"),
        ),
        migrations.DeleteModel(
            name="EventImage",
        ),
    ]
