# Generated by Django 5.2.6 on 2025-12-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0012_event_image_file_delete_eventimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
